export default () => ({
  port: parseInt(process.env.PORT!, 10),
  mongoUri: process.env.MONGO_URI,
  access_secret: process.env.JWT_ACCESS_SECRET as string,
  access_expires: process.env.JWT_ACCESS_EXPIRES as string,
  tmp_secret: process.env.JWT_TEMP_SECRET as string,
  tmp_expires: process.env.JWT_TEMP_EXPIRES as string,
  refresh_secret: process.env.JWT_REFRESH_SECRET as string,
  refresh_expires: process.env.JWT_REFRESH_EXPIRES as string,
  client_url: process.env.CLIENT_URL as string,
  redis: {
    host: process.env.REDIS_HOST,
    port: parseInt(process.env.REDIS_PORT!, 10),
  },
  aws: {
    s3Bucket: process.env.AWS_S3_BUCKET,
    region: process.env.AWS_REGION,
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    cloudFrontKeyPairId: process.env.AWS_CLOUDFRONT_KEY_PAIR_ID,
    cloudFrontDomain: process.env.AWS_CLOUDFRONT_DOMAIN,
  },
  ai: {
    api_key: process.env.OPENROUTER_API_KEY,
    model: process.env.OPENROUTER_MODEL,
    embeddingModel: process.env.EMBEDDING_MODEL,
    base_url: process.env.OPENROUTER_BASE_URL,
    botId: process.env.BOT_ID,
  },
});
