services:
  redis:
    image: redis:7-alpine
    container_name: zalo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  backend:
    image: ${DOCKER_USERNAME}/zola-backend:latest
    container_name: zalo-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

volumes:
  redis_data: