services:
  redis:
    image: redis:7-alpine
    container_name: zalo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  web:
    image: htuan04/zola-web:latest
    container_name: zalo-web
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  backend:
    image: htuan04/zola-backend:latest
    container_name: zalo-backend
    env_file:
      - .env
    volumes:
      - ./secrets:/app/secrets
    depends_on:
      - redis
    restart: always

volumes:
  redis_data: